import * as db from "./db";

/**
 * Top 100 blogs from user - directly seeded into database
 */
const TOP_100_BLOGS = [
  { domain: "paulgraham.com", author: "Paul Graham", bio: "Co-founder of Y Combinator, entrepreneur, and essayist", topics: "startups, technology, entrepreneurship", totalScore: 97538, storiesCount: 392 },
  { domain: "krebsonsecurity.com", author: "Brian Krebs", bio: "Independent journalist", topics: "security, malware, fraud", totalScore: 89989, storiesCount: 491 },
  { domain: "simonwillison.net", author: "Simon Willison", bio: "AI researcher and co-creator of Django", topics: "AI, data journalism, blogging", totalScore: 65841, storiesCount: 278 },
  { domain: "daringfireball.net", author: "John Gruber", bio: "Technology blogger", topics: "Apple, technology, design", totalScore: 54000, storiesCount: 452 },
  { domain: "jvns.ca", author: "Julia Evans", bio: "Developer and zine author", topics: "linux, debugging, dns", totalScore: 50777, storiesCount: 249 },
  { domain: "danluu.com", author: "Dan Luu", bio: "Engineer and writer", topics: "hardware, software, performance", totalScore: 48382, storiesCount: 210 },
  { domain: "righto.com", author: "Ken Shirriff", bio: "Vintage computer enthusiast", topics: "computer history, vintage computers, reverse engineering", totalScore: 46382, storiesCount: 330 },
  { domain: "stratechery.com", author: "Ben Thompson", bio: "Technology analyst", topics: "business, technology, media", totalScore: 45818, storiesCount: 265 },
  { domain: "troyhunt.com", author: "Troy Hunt", bio: "Security expert and instructor", topics: "security, data breaches, web security", totalScore: 43674, storiesCount: 184 },
  { domain: "rachelbythebay.com", author: "Rachel Kroll", bio: "Infrastructure engineer", topics: "software engineering, personal experiences, technology", totalScore: 42586, storiesCount: 240 },
  { domain: "shkspr.mobi", author: "Terence Eden", bio: "Technology consultant and writer", topics: "open data, technology, digital rights", totalScore: 42531, storiesCount: 265 },
  { domain: "schneier.com", author: "Bruce Schneier", bio: "Security technologist and author", topics: "security, cryptography, privacy", totalScore: 41309, storiesCount: 387 },
  { domain: "kalzumeus.com", author: "Patrick McKenzie", bio: "Developer and consultant", topics: "product pricing, a-b testing, conversion optimization", totalScore: 41254, storiesCount: 179 },
  { domain: "jacquesmattheij.com", author: "Jacques Mattheij", bio: "Entrepreneur and technologist", topics: "startups, technology, personal projects", totalScore: 39511, storiesCount: 231 },
  { domain: "jeffgeerling.com", author: "Jeff Geerling", bio: "Developer and YouTube creator", topics: "Raspberry Pi, Ansible, open-source", totalScore: 37733, storiesCount: 202 },
  { domain: "utcc.utoronto.ca/~cks", author: "Chris Siebenmann", bio: "Unix system administrator at University of Toronto", topics: "Unix, system administration, linux", totalScore: 37204, storiesCount: 332 },
  { domain: "blog.samaltman.com", author: "Sam Altman", bio: "Entrepreneur and investor", topics: "startups, technology, economics", totalScore: 36060, storiesCount: 131 },
  { domain: "antirez.com", author: "Salvatore Sanfilippo", bio: "Creator of Redis", topics: "databases, open-source, software development", totalScore: 34918, storiesCount: 160 },
  { domain: "marco.org", author: "Marco Arment", bio: "Developer and podcaster", topics: "technology, software development, podcasts", totalScore: 34547, storiesCount: 237 },
  { domain: "blog.codinghorror.com", author: "Jeff Atwood", bio: "Developer and co-founder of Stack Overflow", topics: "software development, coding practices, technology", totalScore: 32739, storiesCount: 293 },
  { domain: "drewdevault.com", author: "Drew DeVault", bio: "Developer and open-source advocate", topics: "open-source, software development, technology", totalScore: 32409, storiesCount: 184 },
  { domain: "ciechanow.ski", author: "Bartosz Ciechanowski", bio: "Author of interactive articles", topics: "physics, engineering, visualizations", totalScore: 32271, storiesCount: 26 },
  { domain: "tbray.org", author: "Tim Bray", bio: "Technologist and writer", topics: "technology, software development, XML", totalScore: 31428, storiesCount: 217 },
  { domain: "sive.rs", author: "Derek Sivers", bio: "Entrepreneur and author", topics: "entrepreneurship, music, personal development", totalScore: 29851, storiesCount: 177 },
  { domain: "devblogs.microsoft.com/oldnewthing", author: "Raymond Chen", bio: "Veteran Microsoft engineer", topics: "Windows development, programming, software history", totalScore: 28687, storiesCount: 213 },
  { domain: "fabiensanglard.net", author: "Fabien Sanglard", bio: "Software developer and author", topics: "game development, software engineering, retro computing", totalScore: 28424, storiesCount: 135 },
  { domain: "jgc.org", author: "John Graham-Cumming", bio: "Former CTO of Cloudflare", topics: "programming, technology, history", totalScore: 27450, storiesCount: 245 },
  { domain: "gwern.net", author: "Gwern Branwen", bio: "Researcher and writer", topics: "psychology, statistics, technology", totalScore: 26359, storiesCount: 207 },
  { domain: "daniel.haxx.se", author: "Daniel Stenberg", bio: "Creator of cURL", topics: "networking, open-source, software development", totalScore: 26037, storiesCount: 172 },
  { domain: "johndcook.com", author: "John D. Cook", bio: "Consultant and mathematician", topics: "mathematics, statistics, software development", totalScore: 23292, storiesCount: 239 },
  { domain: "steveblank.com", author: "Steve Blank", bio: "Entrepreneur and educator", topics: "startups, entrepreneurship, lean startup methodology", totalScore: 23076, storiesCount: 214 },
  { domain: "pluralistic.net", author: "Cory Doctorow", bio: "Author and activist", topics: "activism, technology, copyright", totalScore: 22161, storiesCount: 162 },
  { domain: "martinfowler.com", author: "Martin Fowler", bio: "Software development expert", topics: "software architecture, refactoring, agile development", totalScore: 21682, storiesCount: 162 },
  { domain: "tonsky.me", author: "Nikita Prokopov", bio: "Developer and designer", topics: "software development, design, typography", totalScore: 21451, storiesCount: 63 },
  { domain: "lemire.me", author: "Daniel Lemire", bio: "Computer science professor", topics: "algorithms, performance, data science", totalScore: 21087, storiesCount: 216 },
  { domain: "hanselman.com", author: "Scott Hanselman", bio: "Developer and speaker", topics: "software development, productivity, technology", totalScore: 20431, storiesCount: 127 },
  { domain: "gatesnotes.com", author: "Bill Gates", bio: "Philanthropist and technologist", topics: "global health, education, technology", totalScore: 20141, storiesCount: 88 },
  { domain: "dynomight.net", author: "Anonymous", bio: "", topics: "science, existential angst", totalScore: 20127, storiesCount: 90 },
  { domain: "neal.fun", author: "Neal Agarwal", bio: "Interactive web developer and designer", topics: "web development, creative coding, interactive design", totalScore: 19980, storiesCount: 29 },
  { domain: "filfre.net", author: "Jimmy Maher", bio: "Writer and historian", topics: "computer history, interactive fiction, technology", totalScore: 19373, storiesCount: 146 },
  { domain: "nullprogram.com", author: "Chris Wellons", bio: "Software developer", topics: "programming, emacs, software engineering", totalScore: 18795, storiesCount: 143 },
  { domain: "antipope.org", author: "Charles Stross", bio: "Science fiction author", topics: "science fiction, technology, politics", totalScore: 18276, storiesCount: 136 },
  { domain: "blog.plover.com", author: "Mark Dominus", bio: "Software developer and amateur mathematician", topics: "languages, programming, books", totalScore: 18079, storiesCount: 110 },
  { domain: "xeiaso.net", author: "Xe Iaso", bio: "Software developer and creator of Anubis", topics: "software development, Rust programming, Nix", totalScore: 17882, storiesCount: 100 },
  { domain: "mjg59.dreamwidth.org", author: "Matthew Garrett", bio: "Security developer", topics: "security, Linux, open-source", totalScore: 17746, storiesCount: 115 },
  { domain: "blog.acolyer.org", author: "Adrian Colyer", bio: "Technology analyst", topics: "computer science research, technology, software engineering", totalScore: 17622, storiesCount: 182 },
  { domain: "brendangregg.com", author: "Brendan Gregg", bio: "Performance engineer", topics: "performance engineering, systems, technology", totalScore: 17548, storiesCount: 86 },
  { domain: "idlewords.com", author: "Maciej Cegłowski", bio: "Developer and writer", topics: "technology, culture, travel", totalScore: 17219, storiesCount: 81 },
  { domain: "lucumr.pocoo.org", author: "Armin Ronacher", bio: "Software developer and creator of Flask", topics: "Python, open-source, software development", totalScore: 17184, storiesCount: 108 },
  { domain: "slatestarcodex.com", author: "Scott Alexander", bio: "Psychiatrist and blogger", topics: "rationality, psychology, culture", totalScore: 17128, storiesCount: 105 },
  { domain: "pragmaticengineer.com", author: "Gergely Orosz", bio: "Software engineer", topics: "software engineering, career development, technology", totalScore: 16700, storiesCount: 84 },
  { domain: "mtlynch.io", author: "Michael Lynch", bio: "Indie founder and s'mores enthusiast", topics: "software engineering, entrepreneurship, homelab", totalScore: 16572, storiesCount: 43 },
  { domain: "daemonology.net", author: "Colin Percival", bio: "FreeBSD contributor and founder of Tarsnap", topics: "security, backups, open-source", totalScore: 15991, storiesCount: 113 },
  { domain: "blog.cryptographyengineering.com", author: "Matthew Green", bio: "Cryptographer", topics: "cryptography, security, privacy", totalScore: 15782, storiesCount: 84 },
  { domain: "scottaaronson.com", author: "Scott Aaronson", bio: "Computer science professor", topics: "quantum computing, computer science, philosophy", totalScore: 15703, storiesCount: 132 },
  { domain: "justine.lol", author: "Justine Tunney", bio: "Software developer and creator of cosmopolitan libc", topics: "programming, operating systems, technology", totalScore: 15082, storiesCount: 40 },
  { domain: "buttondown.com/hillelwayne", author: "Hillel Wayne", bio: "Consultant and author", topics: "formal methods, software engineering, technology", totalScore: 15069, storiesCount: 95 },
  { domain: "joelonsoftware.com", author: "Joel Spolsky", bio: "Software developer and entrepreneur", topics: "software development, startups, project management", totalScore: 14782, storiesCount: 137 },
  { domain: "prog21.dadgum.com", author: "James Hague", bio: "Game designer and software developer", topics: "software development, game development", totalScore: 14761, storiesCount: 138 },
  { domain: "astralcodexten.com", author: "Scott Alexander", bio: "Psychiatrist and blogger", topics: "rationalism, psychology, culture", totalScore: 14531, storiesCount: 121 },
  { domain: "randomascii.wordpress.com", author: "Bruce Dawson", bio: "Software developer", topics: "programming, debugging, performance", totalScore: 14411, storiesCount: 82 },
  { domain: "zachholman.com", author: "Zach Holman", bio: "Developer and speaker", topics: "software development, startups, GitHub", totalScore: 14388, storiesCount: 76 },
  { domain: "seangoedecke.com", author: "Sean Goedecke", bio: "Writer and software developer", topics: "writing, programming, personal projects", totalScore: 14279, storiesCount: 62 },
  { domain: "acoup.blog", author: "Bret Devereaux", bio: "Historian", topics: "history, military history, culture", totalScore: 14163, storiesCount: 112 },
  { domain: "eli.thegreenplace.net", author: "Eli Bendersky", bio: "Software developer", topics: "programming, compilers, technology", totalScore: 14065, storiesCount: 150 },
  { domain: "hillelwayne.com", author: "Hillel Wayne", bio: "Consultant and author", topics: "formal methods, software engineering, technology", totalScore: 14050, storiesCount: 83 },
  { domain: "worrydream.com", author: "Bret Victor", bio: "Designer and engineer", topics: "user interfaces, programming, technology", totalScore: 14015, storiesCount: 86 },
  { domain: "catonmat.net", author: "Peteris Krumins", bio: "Developer and entrepreneur", topics: "programming, productivity, technology", totalScore: 13978, storiesCount: 153 },
  { domain: "bunniestudios.com", author: "Andrew Huang", bio: "Hacker and hardware developer", topics: "hardware hacking, open-source, technology", totalScore: 13796, storiesCount: 75 },
  { domain: "gabrielweinberg.com", author: "Gabriel Weinberg", bio: "CEO of DuckDuckGo", topics: "privacy, entrepreneurship, technology", totalScore: 13425, storiesCount: 140 },
  { domain: "apenwarr.ca", author: "Avery Pennarun", bio: "CEO of Tailscale", topics: "networking, software development, technology", totalScore: 13224, storiesCount: 81 },
  { domain: "austinhenley.com", author: "Austin Henley", bio: "Software developer and researcher", topics: "programming, software development, research", totalScore: 13157, storiesCount: 63 },
  { domain: "xkcd.com", author: "Randall Munroe", bio: "Cartoonist and author", topics: "comics, science, technology", totalScore: 13125, storiesCount: 140 },
  { domain: "matt.might.net", author: "Matt Might", bio: "Computer science professor", topics: "computer science, healthcare, technology", totalScore: 13105, storiesCount: 107 },
  { domain: "matklad.github.io", author: "Alex Kladov", bio: "Software developer and Rust contributor", topics: "Rust, software development, programming languages", totalScore: 13050, storiesCount: 76 },
  { domain: "filippo.io", author: "Filippo Valsorda", bio: "Security engineer and cryptographer", topics: "security, cryptography, software engineering", totalScore: 12788, storiesCount: 69 },
  { domain: "asmartbear.com", author: "Jason Cohen", bio: "Founder of WPEngine and Smart Bear", topics: "startups, entrepreneurship, software development", totalScore: 12748, storiesCount: 115 },
  { domain: "marginalia.nu", author: "Viktor Lofgren", bio: "Founder of Marginalia search engine", topics: "web development, design, technology", totalScore: 12644, storiesCount: 44 },
  { domain: "stephendiehl.com", author: "Stephen Diehl", bio: "Software developer and Haskell enthusiast", topics: "Haskell, software development, programming languages", totalScore: 12410, storiesCount: 69 },
  { domain: "lcamtuf.substack.com", author: "Michał Zalewski", bio: "Security researcher and author", topics: "security, software development, hacking", totalScore: 12336, storiesCount: 66 },
  { domain: "blog.regehr.org", author: "John Regehr", bio: "Computer science professor", topics: "compilers, software engineering, programming languages", totalScore: 12241, storiesCount: 117 },
  { domain: "robertheaton.com", author: "Robert Heaton", bio: "Software developer", topics: "programming, security, technology", totalScore: 12166, storiesCount: 45 },
  { domain: "aphyr.com", author: "Kyle Kingsbury", bio: "Distributed systems engineer and researcher", topics: "distributed systems, databases, software engineering", totalScore: 12146, storiesCount: 63 },
  { domain: "jwz.org", author: "Jamie Zawinski", bio: "Software developer and early Netscape engineer", topics: "software development, technology, personal blog", totalScore: 11768, storiesCount: 79 },
  { domain: "lapcatsoftware.com", author: "Jeff Johnson", bio: "Apple software developer", topics: "security, macOS, iOS", totalScore: 11684, storiesCount: 62 },
  { domain: "tedium.co", author: "Ernie Smith", bio: "Writer and editor", topics: "obscure history, technology, culture", totalScore: 11604, storiesCount: 89 },
  { domain: "tedunangst.com", author: "Ted Unangst", bio: "Software developer and OpenBSD contributor", topics: "OpenBSD, software development, security", totalScore: 11563, storiesCount: 110 },
  { domain: "bellard.org", author: "Fabrice Bellard", bio: "Software prodigy and creator of FFmpeg and QEMU", topics: "software development, multimedia processing, emulation", totalScore: 11560, storiesCount: 47 },
  { domain: "joshwcomeau.com", author: "Josh W. Comeau", bio: "Software developer and educator", topics: "web development, React, JavaScript", totalScore: 11507, storiesCount: 63 },
  { domain: "yosefk.com", author: "Yosef Mendelsohn", bio: "Software engineer and blogger", topics: "software development, C++, programming languages", totalScore: 11446, storiesCount: 98 },
  { domain: "blog.jim-nielsen.com", author: "Jim Nielsen", bio: "Web developer and designer", topics: "web development, design, technology", totalScore: 11333, storiesCount: 37 },
  { domain: "blog.benjojo.co.uk", author: "Ben Cox", bio: "Software engineer and infrastructure expert", topics: "software development, infrastructure, networking", totalScore: 11289, storiesCount: 57 },
  { domain: "calnewport.com", author: "Cal Newport", bio: "Computer science professor and author", topics: "productivity, deep work, computer science", totalScore: 11227, storiesCount: 85 },
  { domain: "blog.fogus.me", author: "Michael Fogus", bio: "Software developer and author", topics: "functional programming, software development, Clojure", totalScore: 11203, storiesCount: 98 },
  { domain: "fasterthanli.me", author: "Amos Wenger", bio: "Rust enthusiast and YouTube creator", topics: "Rust programming, software development, programming languages", totalScore: 11081, storiesCount: 52 },
  { domain: "berthub.eu", author: "Bert Hubert", bio: "Software developer and entrepreneur", topics: "DNS, software development, technology", totalScore: 11068, storiesCount: 51 },
  { domain: "robert.ocallahan.org", author: "Robert O'Callahan", bio: "Software developer", topics: "programming, debugging, technology", totalScore: 11023, storiesCount: 52 },
  { domain: "minimaxir.com", author: "Max Woolf", bio: "Data scientist and software developer", topics: "data science, machine learning, software development", totalScore: 11005, storiesCount: 67 },
  { domain: "research.swtch.com", author: "Russ Cox", bio: "Principal engineer at Google", topics: "programming, software engineering, Go language", totalScore: 10973, storiesCount: 80 },
  { domain: "evanmiller.org", author: "Evan Miller", bio: "", topics: "statistics, software development, data science", totalScore: 10912, storiesCount: 60 },
];

export async function seedTop100Blogs() {
  console.log("[SeedBlogs] Starting to seed top 100 blogs...");
  try {
    const result = await db.upsertBlogs(
      TOP_100_BLOGS.map((blog) => ({
        domain: blog.domain,
        author: blog.author,
        bio: blog.bio,
        topics: blog.topics,
        totalScore: blog.totalScore,
        storiesCount: blog.storiesCount,
      }))
    );
    console.log(`[SeedBlogs] Successfully seeded ${result.length} blogs`);
    return result;
  } catch (error) {
    console.error("[SeedBlogs] Error seeding blogs:", error);
    throw error;
  }
}
